In [2]:
import os
if not Path("src").is_dir():
    os.chdir(Path.cwd().parent)

from sqlalchemy import create_engine 
import pandas as pd
from pathlib import Path
from src.config import RAW_DIR

engine = create_engine("postgresql+psycopg2://data_admin:TUE123@localhost:5433/cbl_policing")
df_msoa_to_pfa = pd.read_sql("""SELECT * FROM msoa_to_pfa22""", engine).rename(columns={'msoacd': 'MSOA21CD',
                                                                                        'pfa22cd': 'PFA22CD',
                                                                                        'pfa22nm': 'PFA22NM'})
df_msoa_to_pfa.to_csv(RAW_DIR / 'lookup' / 'msoa_pfa_lookup.csv')
df_msoa_to_pfa

       MSOA21CD    PFA22CD              PFA22NM
0     E02000001  E23000034      London, City of
1     E02000002  E23000001  Metropolitan Police
2     E02000003  E23000001  Metropolitan Police
3     E02000004  E23000001  Metropolitan Police
4     E02000005  E23000001  Metropolitan Police
...         ...        ...                  ...
7259  W02000424  W15000001          North Wales
7260  W02000425  W15000001          North Wales
7261  W02000426  W15000001          North Wales
7262  W02000427  W15000003          South Wales
7263  W02000428  W15000003          South Wales

[7264 rows x 3 columns]

In [3]:
df_pfa_officers = pd.read_sql("""SELECT * FROM pfa22_officer_totals""", engine).rename(columns={'pfa22cd': 'PFA22CD',
                                                                                                'total_officers_fte': 'num_officers'})
df_pfa_officers.to_csv(RAW_DIR / 'lookup' / 'pfa_officers_lookup.csv')
df_pfa_officers

      PFA22CD  num_officers
0   E23000001       33293.0
1   E23000002        1365.0
2   E23000003        3561.0
3   E23000004        4159.0
4   E23000005        8112.0
5   E23000006        2395.0
6   E23000007        3829.0
7   E23000008        1376.0
8   E23000009        1655.0
9   E23000010        6138.0
10  E23000011        3026.0
11  E23000012        2273.0
12  E23000013        1520.0
13  E23000014        7991.0
14  E23000015        1997.0
15  E23000016        2509.0
16  E23000017        1131.0
17  E23000018        2102.0
18  E23000019        2391.0
19  E23000020        1173.0
20  E23000021        2248.0
21  E23000022        1465.0
22  E23000023        1720.0
23  E23000024        1911.0
24  E23000025        1403.0
25  E23000026        1481.0
26  E23000027        2379.0
27  E23000028        3760.0
28  E23000029        5000.0
29  E23000030        3370.0
30  E23000031        2330.0
31  E23000032        4168.0
32  E23000033        3206.0
33  E23000034         992.0
34  E23000035        3618.0
35  E23000036        3327.0
36  E23000037        1346.0
37  E23000038        1213.0
38  E23000039        1420.0
39  W15000001        1736.0
40  W15000002        1549.0
41  W15000003        3511.0
42  W15000004        1291.0